bg01:
  name: 甜美的家
  file: 01 甜美的家.webp
bg02:
  name: 宿舍走廊
  file: 02 宿舍走廊.webp
bg03:
  name: 牢房走廊
  file: 03 牢房走廊.webp
bg04:
  name: 房间转角
  file: 04 房间转角.webp
bg05:
  name: 会客大厅
  file: 05 会客大厅.webp
bg06:
  name: 烛光晚餐
  file: 06 烛光晚餐.webp
bg07:
  name: 卧室
  file: 07 夜晚卧室.webp
  variants: 
    bg07:
      name: 夜晚
      file: 07 夜晚卧室.webp
    bg08:
      name: 白天
      file: 08 白天卧室.webp
bg09:
  name: 走廊
  file: 09 白天走廊.webp
  variants: 
    bg09:
      name: 白天
      file: 09 白天走廊.webp
    bg10:
      name: 夜晚
      file: 10 夜晚走廊.webp
bg11:
  name: 楼梯转角
  file: 11 楼梯转角.webp
bg12:
  name: 多功能厅
  file: 12 多功能厅.webp
bg13:
  name: 大图书馆
  file: 13 大图书馆.webp
bg14:
  name: 原审启动
  file: 14 原审启动.webp
bg15:
  name: 证人席位
  file: 15 证人席位.webp
bg16:
  name: 蓝天绿草
  file: 16 蓝天绿草.webp
bg17:
  name: 森林
  file: 17 白天森林.webp
  variants: 
    bg17:
      name: 白天
      file: 17 白天森林.webp
    bg18:
      name: 夜晚
      file: 18 夜晚森林.webp
bg19:
  name: 墙壁
  file: 19 白天墙壁.webp
bg20:
  name: 洋馆
  file: 20 白天洋馆.webp
  variants: 
    bg20:
      name: 白天
      file: 20 白天洋馆.webp
    bg21:
      name: 夜晚
      file: 21 夜晚洋馆.webp
bg22:
  name: 小区
  file: 22 白天小区.webp
  variants: 
    bg22:
      name: 白天
      file: 22 白天小区.webp
    bg23:
      name: 夜晚
      file: 23 夜晚小区.webp
bg24:
  name: 木屋
  file: 24 白天木屋.webp
  variants: 
    bg24:
      name: 白天
      file: 24 白天木屋.webp
    bg25:
      name: 夜晚
      file: 25 夜晚木屋.webp
bg26:
  name: 仓库
  file: 26 白天仓库.webp
bg27:
  name: 控制室吧
  file: 27 控制室吧.webp
bg28:
  name: 花园
  file: 28 白天花园.webp
  variants: 
    bg28:
      name: 白天
      file: 28 白天花园.webp
    bg29:
      name: 夜晚
      file: 29 夜晚花园.webp
bg30:
  name: 艺术画廊
  file: 30 艺术画廊.webp
  variants: 
    bg30:
      name: 白天
      file: 30 艺术画廊.webp
    bg31:
      name: 夜晚
      file: 31 夜晚画廊.webp
bg32:
  name: 机械电梯
  file: 32 机械电梯.webp