'16:9':
  aspect_ratio: '16:9'
  bracket_color: '#ef4f54'
  font_family: font3
  font_size: 55
  image_components:
  - align: bottom-left
    enabled: true
    layer: 0
    offset_x: 900
    offset_y: -800
    overlay: ''
    scale: 1.4
    type: character
  - align: bottom-center
    enabled: true
    layer: 1
    offset_x: 0
    offset_y: 0
    overlay: 文本框1.webp
    scale: 1.0
    type: textbox
  - align: bottom-left
    enabled: true
    layer: 2
    offset_x: 200
    offset_y: -300
    overlay: 名字框.webp
    scale: 1.0
    type: namebox
  - align: top-left
    enabled: true
    id: extra_2
    layer: 3
    offset_x: 20
    offset_y: 20
    overlay: 书-左上.webp
    scale: 1.0
    type: extra
  - align: top-right
    enabled: true
    id: extra_3
    layer: 4
    offset_x: 0
    offset_y: 0
    overlay: 枝叶-右上.webp
    scale: 1.0
    type: extra
  - align: top-right
    enabled: true
    id: extra_1
    layer: 5
    offset_x: 0
    offset_y: 0
    overlay: 齿轮-右上.webp
    scale: 1.0
    type: extra
  shadow_color: '#000000'
  shadow_offset_x: 3
  shadow_offset_y: 3
  text_align: left
  text_color: '#FFFFFF'
  text_valign: top
  textbox_height: 245
  textbox_width: 1579
  textbox_x: 470
  textbox_y: 1080
  use_character_color: true
default:
  aspect_ratio: '3:1'
  bracket_color: '#ef4f54'
  font_family: font3
  font_size: 90
  image_components:
  - align: bottom-center
    enabled: true
    layer: 0
    offset_x: 0
    offset_y: 0
    overlay: 文本框1.webp
    scale: 1.0
    type: textbox
  - align: bottom-left
    enabled: true
    layer: 3
    offset_x: 0
    offset_y: 0
    overlay: ''
    scale: 1.6
    type: character
  - align: bottom-left
    enabled: true
    layer: 4
    offset_x: 450
    offset_y: -400
    overlay: 名字框.webp
    scale: 1.2
    type: namebox
  shadow_color: '#000000'
  shadow_offset_x: 4
  shadow_offset_y: 4
  text_align: left
  text_color: '#FFFFFF'
  text_valign: top
  textbox_height: 445
  textbox_width: 1579
  textbox_x: 760
  textbox_y: 355
  use_character_color: false
